/**
 * Nonce Utility
 *
 * Helper function to retrieve CSP nonce from request headers.
 * The nonce is generated in middleware and passed via x-nonce header.
 *
 * IMPORTANT: For static generation, we use a placeholder nonce that gets
 * replaced by middleware at runtime for actual CSP enforcement.
 */

import { headers } from 'next/headers'

/**
 * Get the CSP nonce for the current request
 *
 * This MUST be called in async server components to retrieve the nonce
 * from request headers. The nonce is generated by middleware and passed
 * via the x-nonce header.
 *
 * @returns The nonce string from request headers
 */
export async function getNonce(): Promise<string> {
  try {
    const headersList = await headers()
    const nonce = headersList.get('x-nonce')
    return nonce || ''
  } catch (error) {
    console.error('[Nonce] Error retrieving nonce from headers:', error)
    return ''
  }
}
